# Generated by Django 4.1.7 on 2023-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_information_description_information_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
