# Generated by Django 4.1.7 on 2023-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_education_information_address_information_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
